<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>markdown</string>
		<string>md</string>
		<string>mdown</string>
		<string>markdn</string>
	</array>
	<key>firstLineMatch</key>
	<string>^%\s</string>
	<key>foldingStartMarker</key>
	<string>(?x)
		(&lt;(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|form|dl)\b.*?&gt;
		|&lt;!--(?!.*--&gt;)
		|\{\s*($|\?&gt;\s*$|//|/\*(.*\*/\s*$|(?!.*?\*/)))
		)</string>
	<key>foldingStopMarker</key>
	<string>(?x)
		(&lt;/(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|form|dl)&gt;
		|^\s*--&gt;
		|(^|\s)\}
		)</string>
	<key>keyEquivalent</key>
	<string>^~P</string>
	<key>name</key>
	<string>Pandoc</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^% (.*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>title.meta.header.multimarkdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^$|^(?=[A-Za-z0-9]+:)</string>
			<key>name</key>
			<string>meta.header.multimarkdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>The reason for not setting scopeName = "string.unquoted" 
						(for the parent rule) is that we do not want
						newlines to be marked as string.unquoted</string>
					<key>match</key>
					<string>.+</string>
					<key>name</key>
					<string>string.unquoted.multimarkdown</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(?!=[A-Za-z0-9]+:)</string>
			<key>end</key>
			<string>^(?=not)possible$</string>
			<key>name</key>
			<string>meta.content.multimarkdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^[ ]{0,3}\[\^(.+?)\]:[ \t]*(.*?)$\n</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.other.reference.footnote.multimarkdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.footnote.multimarkdown</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^$</string>
					<key>name</key>
					<string>meta.footnote.reference.def.multimarkdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.markdown</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^[ ]{0,3}\[\#(.+?)\]:[ \t]*(.*?)$\n</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.other.reference.citation.multimarkdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.citation.multimarkdown</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^$</string>
					<key>name</key>
					<string>meta.citation.reference.def.multimarkdown</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.other.reference.link.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.markdown</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.other.link.description.title.markdown</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>string.other.link.description.attributes.markdown</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x:
						\s*						# Leading whitespace
						\[(.+?)\]:				# Reference name
						[ \t]*					# Optional whitespace
						&lt;?(\S+?)&gt;?				# The url
						[ \t]*					# Optional whitespace
						(?:
							["(](.+?)[")]		# Match title in quotes or parens
							[ \t]*
						)?						# Title is optional
						(
							(?&lt;=\s)				# Match attributes
							(([ \t]*\n)?[ \t]*	# Leading whitespace
								(\S+=\S+)|(\S+=".*?")	# Match the attributes
							)*
						)?[ \t]*				# Attributes are optional
						\s*						# Optional whitespace
						$\n?
					)</string>
					<key>name</key>
					<string>meta.link.reference.def.markdown</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^([ ]{0,3})[^\s\*].*?\|.*|\[.*?\](\[.*?\])?[ \t]*$\n?</string>
					<key>end</key>
					<string>^(?!((.*\|.*)|\[.*\]|$))</string>
					<key>name</key>
					<string>markup.table.multimarkdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.markdown</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.markdown</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.markdown.pandoc</string>
	<key>uuid</key>
	<string>0D462201-2053-435B-8732-9BCC63D7C8C8</string>
</dict>
</plist>
